// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/content.proto

package content

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentInfo struct {
	ContentId            string   `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Brief                string   `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentInfo) Reset()         { *m = ContentInfo{} }
func (m *ContentInfo) String() string { return proto.CompactTextString(m) }
func (*ContentInfo) ProtoMessage()    {}
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{0}
}

func (m *ContentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentInfo.Unmarshal(m, b)
}
func (m *ContentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentInfo.Marshal(b, m, deterministic)
}
func (m *ContentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentInfo.Merge(m, src)
}
func (m *ContentInfo) XXX_Size() int {
	return xxx_messageInfo_ContentInfo.Size(m)
}
func (m *ContentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContentInfo proto.InternalMessageInfo

func (m *ContentInfo) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ContentInfo) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

type GetContentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentRequest) Reset()         { *m = GetContentRequest{} }
func (m *GetContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetContentRequest) ProtoMessage()    {}
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{1}
}

func (m *GetContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentRequest.Unmarshal(m, b)
}
func (m *GetContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentRequest.Marshal(b, m, deterministic)
}
func (m *GetContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentRequest.Merge(m, src)
}
func (m *GetContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetContentRequest.Size(m)
}
func (m *GetContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentRequest proto.InternalMessageInfo

func (m *GetContentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentResponse) Reset()         { *m = GetContentResponse{} }
func (m *GetContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetContentResponse) ProtoMessage()    {}
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{2}
}

func (m *GetContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentResponse.Unmarshal(m, b)
}
func (m *GetContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentResponse.Marshal(b, m, deterministic)
}
func (m *GetContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentResponse.Merge(m, src)
}
func (m *GetContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetContentResponse.Size(m)
}
func (m *GetContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentResponse proto.InternalMessageInfo

func (m *GetContentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListContentsRequest struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContentsRequest) Reset()         { *m = ListContentsRequest{} }
func (m *ListContentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListContentsRequest) ProtoMessage()    {}
func (*ListContentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{3}
}

func (m *ListContentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContentsRequest.Unmarshal(m, b)
}
func (m *ListContentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContentsRequest.Marshal(b, m, deterministic)
}
func (m *ListContentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContentsRequest.Merge(m, src)
}
func (m *ListContentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListContentsRequest.Size(m)
}
func (m *ListContentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContentsRequest proto.InternalMessageInfo

func (m *ListContentsRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *ListContentsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListContentsResponse struct {
	Contents             []*ContentInfo `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	NextPageToken        string         `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListContentsResponse) Reset()         { *m = ListContentsResponse{} }
func (m *ListContentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContentsResponse) ProtoMessage()    {}
func (*ListContentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{4}
}

func (m *ListContentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContentsResponse.Unmarshal(m, b)
}
func (m *ListContentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContentsResponse.Marshal(b, m, deterministic)
}
func (m *ListContentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContentsResponse.Merge(m, src)
}
func (m *ListContentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListContentsResponse.Size(m)
}
func (m *ListContentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContentsResponse proto.InternalMessageInfo

func (m *ListContentsResponse) GetContents() []*ContentInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *ListContentsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type CreateContentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContentRequest) Reset()         { *m = CreateContentRequest{} }
func (m *CreateContentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContentRequest) ProtoMessage()    {}
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{5}
}

func (m *CreateContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContentRequest.Unmarshal(m, b)
}
func (m *CreateContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContentRequest.Marshal(b, m, deterministic)
}
func (m *CreateContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContentRequest.Merge(m, src)
}
func (m *CreateContentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContentRequest.Size(m)
}
func (m *CreateContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContentRequest proto.InternalMessageInfo

func (m *CreateContentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateContentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContentResponse) Reset()         { *m = CreateContentResponse{} }
func (m *CreateContentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContentResponse) ProtoMessage()    {}
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{6}
}

func (m *CreateContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContentResponse.Unmarshal(m, b)
}
func (m *CreateContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContentResponse.Marshal(b, m, deterministic)
}
func (m *CreateContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContentResponse.Merge(m, src)
}
func (m *CreateContentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContentResponse.Size(m)
}
func (m *CreateContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContentResponse proto.InternalMessageInfo

func (m *CreateContentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateContentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContentRequest) Reset()         { *m = UpdateContentRequest{} }
func (m *UpdateContentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContentRequest) ProtoMessage()    {}
func (*UpdateContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{7}
}

func (m *UpdateContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContentRequest.Unmarshal(m, b)
}
func (m *UpdateContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContentRequest.Merge(m, src)
}
func (m *UpdateContentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContentRequest.Size(m)
}
func (m *UpdateContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContentRequest proto.InternalMessageInfo

func (m *UpdateContentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateContentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContentResponse) Reset()         { *m = UpdateContentResponse{} }
func (m *UpdateContentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateContentResponse) ProtoMessage()    {}
func (*UpdateContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{8}
}

func (m *UpdateContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContentResponse.Unmarshal(m, b)
}
func (m *UpdateContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContentResponse.Merge(m, src)
}
func (m *UpdateContentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateContentResponse.Size(m)
}
func (m *UpdateContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContentResponse proto.InternalMessageInfo

func (m *UpdateContentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteContentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContentRequest) Reset()         { *m = DeleteContentRequest{} }
func (m *DeleteContentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContentRequest) ProtoMessage()    {}
func (*DeleteContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{9}
}

func (m *DeleteContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContentRequest.Unmarshal(m, b)
}
func (m *DeleteContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContentRequest.Merge(m, src)
}
func (m *DeleteContentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContentRequest.Size(m)
}
func (m *DeleteContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContentRequest proto.InternalMessageInfo

func (m *DeleteContentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteContentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContentResponse) Reset()         { *m = DeleteContentResponse{} }
func (m *DeleteContentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteContentResponse) ProtoMessage()    {}
func (*DeleteContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c14ac167c37e45, []int{10}
}

func (m *DeleteContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContentResponse.Unmarshal(m, b)
}
func (m *DeleteContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContentResponse.Merge(m, src)
}
func (m *DeleteContentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteContentResponse.Size(m)
}
func (m *DeleteContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContentResponse proto.InternalMessageInfo

func (m *DeleteContentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ContentInfo)(nil), "content.ContentInfo")
	proto.RegisterType((*GetContentRequest)(nil), "content.GetContentRequest")
	proto.RegisterType((*GetContentResponse)(nil), "content.GetContentResponse")
	proto.RegisterType((*ListContentsRequest)(nil), "content.ListContentsRequest")
	proto.RegisterType((*ListContentsResponse)(nil), "content.ListContentsResponse")
	proto.RegisterType((*CreateContentRequest)(nil), "content.CreateContentRequest")
	proto.RegisterType((*CreateContentResponse)(nil), "content.CreateContentResponse")
	proto.RegisterType((*UpdateContentRequest)(nil), "content.UpdateContentRequest")
	proto.RegisterType((*UpdateContentResponse)(nil), "content.UpdateContentResponse")
	proto.RegisterType((*DeleteContentRequest)(nil), "content.DeleteContentRequest")
	proto.RegisterType((*DeleteContentResponse)(nil), "content.DeleteContentResponse")
}

func init() { proto.RegisterFile("idl/content.proto", fileDescriptor_d6c14ac167c37e45) }

var fileDescriptor_d6c14ac167c37e45 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x8a, 0xda, 0x40,
	0x14, 0xc6, 0xfd, 0x53, 0xab, 0x1e, 0x6b, 0x8b, 0xd3, 0x14, 0x42, 0xac, 0x45, 0xd2, 0x62, 0xbd,
	0xd2, 0x62, 0xdf, 0xa0, 0x96, 0x8a, 0xd0, 0x82, 0xa4, 0xbb, 0xb0, 0xec, 0x8d, 0xa8, 0x39, 0x66,
	0x87, 0x75, 0x33, 0xd9, 0xcc, 0x08, 0x8b, 0x2f, 0xb2, 0xaf, 0xbb, 0x24, 0x99, 0xc4, 0x89, 0x4e,
	0x58, 0xaf, 0x32, 0x73, 0xce, 0x97, 0xdf, 0x49, 0xbe, 0x6f, 0x18, 0xe8, 0x50, 0x77, 0x37, 0xde,
	0x30, 0x5f, 0xa0, 0x2f, 0x46, 0x41, 0xc8, 0x04, 0x23, 0x75, 0xb9, 0xb5, 0x6f, 0xa0, 0x35, 0x4d,
	0x96, 0x73, 0x7f, 0xcb, 0x48, 0x0f, 0x40, 0x76, 0x96, 0xd4, 0x35, 0xcb, 0xfd, 0xf2, 0xb0, 0xe9,
	0x34, 0x65, 0x65, 0xee, 0x12, 0x03, 0x6a, 0x82, 0x8a, 0x1d, 0x9a, 0x95, 0xb8, 0x93, 0x6c, 0xa2,
	0xea, 0x3a, 0xa4, 0xb8, 0x35, 0xab, 0x49, 0x35, 0xde, 0xd8, 0x5f, 0xa1, 0x33, 0x43, 0x21, 0xe1,
	0x0e, 0x3e, 0xee, 0x91, 0x0b, 0xf2, 0x1e, 0x2a, 0x19, 0xb7, 0x42, 0x5d, 0xfb, 0x1b, 0x10, 0x55,
	0xc4, 0x03, 0xe6, 0x73, 0x3c, 0x53, 0xfd, 0x81, 0x8f, 0x7f, 0x29, 0x4f, 0x65, 0x3c, 0x85, 0x11,
	0x78, 0x13, 0xac, 0x3c, 0x94, 0xc2, 0x78, 0x4d, 0xba, 0xd0, 0x8c, 0x9e, 0x4b, 0x4e, 0x0f, 0xc9,
	0x57, 0xd6, 0x9c, 0x46, 0x54, 0xf8, 0x4f, 0x0f, 0x68, 0x07, 0x60, 0xe4, 0x39, 0x72, 0xde, 0x0f,
	0x68, 0xc8, 0x7f, 0xe4, 0x66, 0xb9, 0x5f, 0x1d, 0xb6, 0x26, 0xc6, 0x28, 0xf5, 0x4b, 0x71, 0xc7,
	0xc9, 0x54, 0x64, 0x00, 0x1f, 0x7c, 0x7c, 0x12, 0xcb, 0x78, 0x96, 0x60, 0xf7, 0xe8, 0x4b, 0x4b,
	0xda, 0x51, 0x79, 0xb1, 0xf2, 0xf0, 0x2a, 0x2a, 0xda, 0x03, 0x30, 0xa6, 0x21, 0xae, 0x04, 0xbe,
	0xe2, 0xc3, 0x77, 0xf8, 0x74, 0xa2, 0x2b, 0xb0, 0x62, 0x00, 0xc6, 0x75, 0xe0, 0x5e, 0x04, 0x3c,
	0xd1, 0x15, 0x03, 0x7f, 0xe3, 0x0e, 0x2f, 0x01, 0x9e, 0xe8, 0xf4, 0xc0, 0xc9, 0x73, 0x15, 0xea,
	0x52, 0x43, 0x66, 0x00, 0xc7, 0x78, 0x89, 0x95, 0x99, 0x7a, 0x76, 0x30, 0xac, 0xae, 0xb6, 0x97,
	0x8c, 0xb0, 0x4b, 0xe4, 0x1f, 0xbc, 0x53, 0x93, 0x23, 0x9f, 0x33, 0xb9, 0xe6, 0x60, 0x58, 0xbd,
	0x82, 0x6e, 0x86, 0x5b, 0x40, 0x3b, 0x67, 0x37, 0x39, 0xbe, 0xa1, 0x8b, 0xcb, 0xfa, 0x52, 0xd4,
	0x56, 0x89, 0x39, 0xbf, 0x15, 0xa2, 0x2e, 0x2f, 0x85, 0xa8, 0x8d, 0x29, 0x21, 0xe6, 0x0c, 0x57,
	0x88, 0xba, 0xc0, 0x14, 0xa2, 0x36, 0x27, 0xbb, 0xf4, 0xab, 0x77, 0xdb, 0xf5, 0xa8, 0xb8, 0xdb,
	0xaf, 0x47, 0x1b, 0xf6, 0x30, 0xe6, 0x7b, 0xdf, 0x65, 0x5e, 0xe8, 0xa6, 0x37, 0xc3, 0xfa, 0x6d,
	0x7c, 0x35, 0xfc, 0x7c, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x7c, 0xbf, 0x34, 0x2f, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentClient interface {
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	ListContents(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error)
	CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error)
	UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error)
	DeleteContent(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error)
}

type contentClient struct {
	cc *grpc.ClientConn
}

func NewContentClient(cc *grpc.ClientConn) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, "/content.Content/GetContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ListContents(ctx context.Context, in *ListContentsRequest, opts ...grpc.CallOption) (*ListContentsResponse, error) {
	out := new(ListContentsResponse)
	err := c.cc.Invoke(ctx, "/content.Content/ListContents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error) {
	out := new(CreateContentResponse)
	err := c.cc.Invoke(ctx, "/content.Content/CreateContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error) {
	out := new(UpdateContentResponse)
	err := c.cc.Invoke(ctx, "/content.Content/UpdateContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteContent(ctx context.Context, in *DeleteContentRequest, opts ...grpc.CallOption) (*DeleteContentResponse, error) {
	out := new(DeleteContentResponse)
	err := c.cc.Invoke(ctx, "/content.Content/DeleteContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
type ContentServer interface {
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	ListContents(context.Context, *ListContentsRequest) (*ListContentsResponse, error)
	CreateContent(context.Context, *CreateContentRequest) (*CreateContentResponse, error)
	UpdateContent(context.Context, *UpdateContentRequest) (*UpdateContentResponse, error)
	DeleteContent(context.Context, *DeleteContentRequest) (*DeleteContentResponse, error)
}

func RegisterContentServer(s *grpc.Server, srv ContentServer) {
	s.RegisterService(&_Content_serviceDesc, srv)
}

func _Content_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.Content/GetContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ListContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.Content/ListContents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListContents(ctx, req.(*ListContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_CreateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).CreateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.Content/CreateContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).CreateContent(ctx, req.(*CreateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_UpdateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).UpdateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.Content/UpdateContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).UpdateContent(ctx, req.(*UpdateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.Content/DeleteContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteContent(ctx, req.(*DeleteContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Content_serviceDesc = grpc.ServiceDesc{
	ServiceName: "content.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContent",
			Handler:    _Content_GetContent_Handler,
		},
		{
			MethodName: "ListContents",
			Handler:    _Content_ListContents_Handler,
		},
		{
			MethodName: "CreateContent",
			Handler:    _Content_CreateContent_Handler,
		},
		{
			MethodName: "UpdateContent",
			Handler:    _Content_UpdateContent_Handler,
		},
		{
			MethodName: "DeleteContent",
			Handler:    _Content_DeleteContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/content.proto",
}
